export const ROUTES = {
  home: '/',
  books: '/books',
  bookDetail: (id: string) => `/books/${id}`,
  cart: '/cart',
  checkout: '/checkout',
  login: '/login',
  /** Entrada com aba Admin (substitui o fluxo só em /admin/login). */
  loginWithAdminTab: '/login?tab=admin',
  register: '/register',
  profile: '/profile',
  profileOrders: '/profile/orders',
  profileTransactions: '/profile/transactions',
  profileAddresses: '/profile/addresses',
  profileCards: '/profile/cards',
  admin: '/admin',
  adminLogin: '/admin/login',
  adminAnalytics: '/admin/analytics',
  adminOrders: '/admin/orders',
  adminExchanges: '/admin/exchanges',
  adminInventory: '/admin/inventory',
  adminAudit: '/admin/audit',
  adminBooks: '/admin/books',
  adminCustomers: '/admin/customers',
  aiChat: '/ai/chat',
} as const;
